### ISSUE TITLE
Add option to ignore packages (e.g., app-doc/eclass-manpages)

### ISSUE THREAD

**Issue by Flowdalic** [mgorny/smart-live-rebuild#24]
slr always tries to rebuild `app-doc/eclass-manpages-99999999`, I assume that is due the unique design this particular live ebuild. Not sure if much can be done about it, so my best idea is to have an slr option that allows the user to specify certain packages, like eclass-manpages, from being ignored.

**Comment by Sneethe** [comment]
@Flowdalic You can already do this with --filter-packages flag. Run `smart-live-rebuild -h` for more information.
For a more permanent solution you can put `filter_packages = !cat/pkg` in the conf. To have more than one entry delimit with a comma e.g `filter_packages = !cat/pkg,!foo/bar` etc.

This excellent utility should really have itself a page on the wiki.

**Comment by Sneethe** [comment]
Even more info about the package filtering feature is hidden on the main readme page. https://github.com/projg2/smart-live-rebuild/blob/master/README#L114

**Comment by Flowdalic** [comment]
Thanks, `--filter-packages` looks like it does the trick.
