### ISSUE TITLE
if github.com doesnt resolve, smart-live-rebuild command attempts to rebuild everything..fails

### ISSUE THREAD

**Issue by whatamesss** [mgorny/smart-live-rebuild#25]
i stopped my dns server, and ran smart-live-rebuild to reproduce the error, but it didnt do it this time..

 smart-live-rebuild -d
WARNING:pkgcore:repos.conf: parsing '/etc/portage/repos.conf/gentoo.conf': overriding 'gentoo' repo
*** Forking to drop superuser privileges ...
*** Updating the repositories using 6 parallel jobs...
->  https://github.com/mltframework/shotcut/ [HEAD]
--> git ls-remote https://github.com/mltframework/shotcut/ HEAD
->  https://github.com/WayfireWM/wf-shell.git [HEAD]
--> git ls-remote https://github.com/WayfireWM/wf-shell.git HEAD
->  https://github.com/jirutka/swaylock-effects.git [HEAD]
--> git ls-remote https://github.com/jirutka/swaylock-effects.git HEAD
->  https://github.com/WayfireWM/wf-config.git [HEAD]
--> git ls-remote https://github.com/WayfireWM/wf-config.git HEAD
->  https://github.com/WayfireWM/wayfire.git [HEAD]
--> git ls-remote https://github.com/WayfireWM/wayfire.git HEAD
fatal: unable to access 'https://github.com/WayfireWM/wayfire.git/': Could not resolve host: github.com
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.12/smart-live-rebuild", line 8, in <module>
    sys.exit(setuptools_main())
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/smartliverebuild/cli.py", line 255, in setuptools_main
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/smartliverebuild/cli.py", line 228, in main
    packages = SmartLiveRebuild(opts, pm, cliargs=args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/smartliverebuild/core.py", line 154, in SmartLiveRebuild
    if loop_iter((opts.jobs == 1)):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/smartliverebuild/core.py", line 96, in loop_iter
    ret = vcs(blocking)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/smartliverebuild/vcs/__init__.py", line 174, in __call__
    return self._endupdate()
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/smartliverebuild/vcs/__init__.py", line 243, in _endupdate
    raise Exception("update command returned non-zero result")
Exception: update command returned non-zero result
# fatal: unable to access 'https://github.com/mltframework/shotcut/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/WayfireWM/wf-shell.git/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/jirutka/swaylock-effects.git/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/WayfireWM/wf-config.git/': Could not resolve host: github.com

**Comment by mgorny** [comment]
That's by design. When fetching fails, it can't tell whether it's a temporary problem, or perhaps the `EGIT_REPO_URI` in ebuild changed and it's trying to fetch from the old repository — in which case rebuilding is necessary to update the metadata (nevertheless, this still isn't perfect and won't catch moving repos when the old URI still works). If you don't have it to rebuild on errors `-E` option is available.
